### ISSUE TITLE
what image do you use in the gitlab-ci ?

### ISSUE THREAD

**Issue by zacksleo** [dmstr/yii2-web#2]
I try to use gitlab-ci to run test by codeception just like you. So I clone the code to the gitlab to run, but don't know what image should I use for the CI .

**Comment by schmunk42** [comment]
Sorry for the late response. We're using a super-minimal Yii2 application image in our tests for extensions, see https://github.com/dmstr/yii2-web/blob/master/tests/Dockerfile#L1

**Comment by zacksleo** [comment]
thanks
